module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src', '<rootDir>/tests'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.enum.ts',
    '!src/**/*.constant.ts',
    '!src/server.ts',
    '!src/types/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  coverageThreshold: {
    global: {
      branches: 70,
      functions: 70,
      lines: 70,
      statements: 70,
    },
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@config/(.*)$': '<rootDir>/src/configs/$1',
    '^@controllers/(.*)$': '<rootDir>/src/app/controllers/$1',
    '^@services/(.*)$': '<rootDir>/src/app/services/$1',
    '^@repositories/(.*)$': '<rootDir>/src/app/repositories/$1',
    '^@models/(.*)$': '<rootDir>/src/database/models/$1',
    '^@middlewares/(.*)$': '<rootDir>/src/shared/middlewares/$1',
    '^@validators/(.*)$': '<rootDir>/src/shared/validators/$1',
    '^@utils/(.*)$': '<rootDir>/src/shared/utils/$1',
    '^@constants/(.*)$': '<rootDir>/src/shared/constants/$1',
    '^@interfaces/(.*)$': '<rootDir>/src/interfaces/$1',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@jobs/(.*)$': '<rootDir>/src/features/jobs/$1',
    '^@queue/(.*)$': '<rootDir>/src/features/queue/$1',
    '^@events/(.*)$': '<rootDir>/src/features/events/$1',
    '^@listeners/(.*)$': '<rootDir>/src/features/listeners/$1',
    '^@docs/(.*)$': '<rootDir>/src/docs/$1',
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  testPathIgnorePatterns: ['/node_modules/', '/dist/', '/coverage/'],
  setupFilesAfterEnv: ['<rootDir>/tests/setup.ts'],
  testTimeout: 30000,
  verbose: true,
  detectOpenHandles: true,
  forceExit: true,
  clearMocks: true,
  resetMocks: true,
  restoreMocks: true,
  globals: {
    'ts-jest': {
      tsconfig: {
        esModuleInterop: true,
        allowSyntheticDefaultImports: true,
      },
    },
  },
};
