import {
  En_PermissionAction,
  En_PermissionCategory,
} from '../../shared/constants/enum.constant';
import { PERMISSION_RESOURCES } from '../../shared/constants/global.constant';
import { DataSource } from 'typeorm';
import { Permission } from '../models/permission.model';

const PERMISSION_DEFINITIONS = [
  {
    name: 'Create Users',
    slug: 'users_create',
    description: 'Create new users in the system',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.CREATE,
    isSystem: true,
  },
  {
    name: 'Read Users',
    slug: 'users_read',
    description: 'View user details',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.READ,
    isSystem: true,
  },
  {
    name: 'Update Users',
    slug: 'users_update',
    description: 'Update user information',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.UPDATE,
    isSystem: true,
  },
  {
    name: 'Delete Users',
    slug: 'users_delete',
    description: 'Delete users from the system',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.DELETE,
    isSystem: true,
  },
  {
    name: 'List Users',
    slug: 'users_list',
    description: 'View list of all users',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.LIST,
    isSystem: true,
  },
  {
    name: 'Manage Users',
    slug: 'users_manage',
    description: 'Full access to manage users',
    category: En_PermissionCategory.USER,
    resource: PERMISSION_RESOURCES.USERS,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },

  // Role permissions
  {
    name: 'Create Roles',
    slug: 'roles_create',
    description: 'Create new roles',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.CREATE,
    isSystem: true,
  },
  {
    name: 'Read Roles',
    slug: 'roles_read',
    description: 'View role details',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.READ,
    isSystem: true,
  },
  {
    name: 'Update Roles',
    slug: 'roles_update',
    description: 'Update role information',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.UPDATE,
    isSystem: true,
  },
  {
    name: 'Delete Roles',
    slug: 'roles_delete',
    description: 'Delete roles from the system',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.DELETE,
    isSystem: true,
  },
  {
    name: 'List Roles',
    slug: 'roles_list',
    description: 'View list of all roles',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.LIST,
    isSystem: true,
  },
  {
    name: 'Manage Roles',
    slug: 'roles_manage',
    description: 'Full access to manage roles',
    category: En_PermissionCategory.ROLE,
    resource: PERMISSION_RESOURCES.ROLES,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },

  // Permission permissions
  {
    name: 'Create Permissions',
    slug: 'permissions_create',
    description: 'Create new permissions',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.CREATE,
    isSystem: true,
  },
  {
    name: 'Read Permissions',
    slug: 'permissions_read',
    description: 'View permission details',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.READ,
    isSystem: true,
  },
  {
    name: 'Update Permissions',
    slug: 'permissions_update',
    description: 'Update permission information',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.UPDATE,
    isSystem: true,
  },
  {
    name: 'Delete Permissions',
    slug: 'permissions_delete',
    description: 'Delete permissions from the system',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.DELETE,
    isSystem: true,
  },
  {
    name: 'List Permissions',
    slug: 'permissions_list',
    description: 'View list of all permissions',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.LIST,
    isSystem: true,
  },
  {
    name: 'Manage Permissions',
    slug: 'permissions_manage',
    description: 'Full access to manage permissions',
    category: En_PermissionCategory.PERMISSION,
    resource: PERMISSION_RESOURCES.PERMISSIONS,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },

  // Item permissions
  {
    name: 'Create Items',
    slug: 'items_create',
    description: 'Create new items',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.CREATE,
    isSystem: true,
  },
  {
    name: 'Read Items',
    slug: 'items_read',
    description: 'View item details',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.READ,
    isSystem: true,
  },
  {
    name: 'Update Items',
    slug: 'items_update',
    description: 'Update item information',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.UPDATE,
    isSystem: true,
  },
  {
    name: 'Delete Items',
    slug: 'items_delete',
    description: 'Delete items from the system',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.DELETE,
    isSystem: true,
  },
  {
    name: 'List Items',
    slug: 'items_list',
    description: 'View list of all items',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.LIST,
    isSystem: true,
  },
  {
    name: 'Manage Items',
    slug: 'items_manage',
    description: 'Full access to manage items',
    category: En_PermissionCategory.ITEM,
    resource: PERMISSION_RESOURCES.ITEMS,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },

  // Reservation permissions
  {
    name: 'Create Reservations',
    slug: 'reservations_create',
    description: 'Create new reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.CREATE,
    isSystem: true,
  },
  {
    name: 'Read Reservations',
    slug: 'reservations_read',
    description: 'View reservation details',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.READ,
    isSystem: true,
  },
  {
    name: 'Update Reservations',
    slug: 'reservations_update',
    description: 'Update reservation information',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.UPDATE,
    isSystem: true,
  },
  {
    name: 'Delete Reservations',
    slug: 'reservations_delete',
    description: 'Delete reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.DELETE,
    isSystem: true,
  },
  {
    name: 'List Reservations',
    slug: 'reservations_list',
    description: 'View list of all reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.LIST,
    isSystem: true,
  },
  {
    name: 'Manage Reservations',
    slug: 'reservations_manage',
    description: 'Full access to manage reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },
  {
    name: 'Approve Reservations',
    slug: 'reservations_approve',
    description: 'Approve pending reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.APPROVE,
    isSystem: true,
  },
  {
    name: 'Reject Reservations',
    slug: 'reservations_reject',
    description: 'Reject pending reservations',
    category: En_PermissionCategory.RESERVATION,
    resource: PERMISSION_RESOURCES.RESERVATIONS,
    action: En_PermissionAction.REJECT,
    isSystem: true,
  },

  // Report permissions
  {
    name: 'View Reports',
    slug: 'reports_view',
    description: 'View system reports',
    category: En_PermissionCategory.REPORT,
    resource: PERMISSION_RESOURCES.REPORTS,
    action: En_PermissionAction.VIEW,
    isSystem: true,
  },
  {
    name: 'Export Reports',
    slug: 'reports_export',
    description: 'Export reports to various formats',
    category: En_PermissionCategory.REPORT,
    resource: PERMISSION_RESOURCES.REPORTS,
    action: En_PermissionAction.EXPORT,
    isSystem: true,
  },

  // System permissions
  {
    name: 'Manage System',
    slug: 'system_manage',
    description: 'Full system management access',
    category: En_PermissionCategory.SYSTEM,
    resource: PERMISSION_RESOURCES.SYSTEM,
    action: En_PermissionAction.MANAGE,
    isSystem: true,
  },
  {
    name: 'View System',
    slug: 'system_view',
    description: 'View system information',
    category: En_PermissionCategory.SYSTEM,
    resource: PERMISSION_RESOURCES.SYSTEM,
    action: En_PermissionAction.VIEW,
    isSystem: true,
  },
];

export const PermissionSeeder = async (dataSource: DataSource) => {
  const repository = dataSource.getRepository(Permission);

  console.log('📦 Seeding Permissions...');
  for (const data of PERMISSION_DEFINITIONS) {
    const exists = await repository.findOneBy({ slug: data.slug });
    if (!exists) {
      const permission = repository.create(data);
      await repository.save(permission);
    }
  }
  console.log('✅ Permissions seeded!');
};
